### ISSUE TITLE
Halloween Update Todo Checklist (WARNING: SPOILERS!)

### ISSUE THREAD

**Issue by Delocuro** [MinestrapTeam/Minestrappolation-2#370]
All of this stuff needs to be finished before we can release the Haloween update: even if it means it comes out a few days late. I'd rather have a late but functional release than an on-time broken one...
- [x] Fix Mana Bush rendering and functionality.
- [x] Add Mana Leaves.
- [x] Add a way to regenerate Mana
  - [ ] Add Mana Potions and Bronze Cauldrons and implement their Distilled Water and elemental essence-absorbing abilities OR
  - [x] Add automatic Mana regeneration.
- [x] Fix Arcane Forge rendering.
- [x] Finalize Arcane Forge GUI functionality.
- [x] Make sure forging spells with multiple elements is possible.
- [ ] Get at least one Spell variety for each category added (making a minimum of 4).
  - [x] For category **Offense**: _Projectile_ Spells
  - [x] For category **Defense**: _Area Shield_ Spells
  - [ ] For category **Alteration**: _Block Transformation_ Spells
  - [ ] For category **Summoning**: _Summon Mob_ Spells
- [x] Make sure cast Spells render correctly (they should generally be made of a cloud of particles -- probably those swirly Potion effect ones).
- [ ] Fix Mana draining while casting Spells (it somehow got broken at some point).
- [ ] Make sure all Spell functionality is correct (including damage or armor protection per elemental potency, etc).
- [ ] **PLAY TEST EVERYTHING AT LEAST TWICE. ALSO MAKE SURE TO TEST EVERYTHING IN MULTIPLAYER**. If I'm back before it's released, I can do this, but we've been getting kind of lazy about this and it's resulted in some bad releases, so I want to make sure this one is decently quality controlled.
- [ ] **Release**, if possible, on the 31st of October.

I won't have access to Steam or Skype until Sunday night, but if you have major questions before then, comment on this issue and I should be able to reply on my phone. Remember: when in doubt, consult the Features List. Unless I haven't added that content to it yet. In which case, don't.
